version: '3'

services:
  php:
    container_name: php
    build: ./docker/php
    depends_on:
      - db
    environment:
      DB_CONNECTION: pgsql
      DB_HOST: db
      DB_PORT: 5432
      DB_DATABASE: todo
      DB_USERNAME: docker
      DB_PASSWORD: docker
    volumes:
    - ./:/var/www/

  nginx:
    image: nginx
    container_name: nginx
    ports:
    - 8000:80
    volumes:
    - ./:/var/www/
    - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
    - php

  db:
    image: postgres
    container_name: db-host
    environment:
      MYSQL_ROOT_PASSWORD: root
      POSTGRES_DB: todo
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      TZ: 'Asia/Tokyo'
    ports:
    - 5432:5432